config/routes.rb
Rails.application.routes.draw do

	root 'players#index'


  get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'

  get 'inscriptions/create'
  get 'inscriptions/destroy'


	get '/meta', to: 'main#meta'

	resources :players, :characters, :spells, :spell_books, :feats do
		member do
			get :delete
		end
	end

	resources :spell_books do
		member do
			post :inscribe
			get :erase
			get :print
		end
	end

	resources :characters do
		member do
			post :train_feat
			get :untrain_feat
			get :print_feats
			get :edit_feat_uses
			post :update_feat_uses
		end
	end

	resources :character_classes
	resources :races

end

app/models/spell_book.rb
class SpellBook < ApplicationRecord

	belongs_to :character
	has_many :inscriptions
	has_many :spells, 
		:through => :inscriptions,
		:dependent => :destroy
	

	validates :name,
		:presence => true,
		:uniqueness => {
			:scope => :character_id,
			:message => "must be unique"
		}

	scope :sorted_name, lambda { order("name ASC") }
end

app/controllers/spell_books_controller.rb
class SpellBooksController < ApplicationController

	before_action :find_char_and_player

	layout :resolve_layout 

  	add_breadcrumb "home", :root_path
  	add_breadcrumb "Players", '\players'
  	

	def show
		@spellbook = SpellBook.find(params[:id])
		spell_list = @spellbook.spells.count > 0 ? Spell.sorted_name - @spellbook.spells : Spell.sorted_name
		@spell_options = spell_list.map{|spell| [spell.name, spell.id]}

		add_breadcrumb @player.name, player_path(@player)
		add_breadcrumb @character.name, character_path(@character, :player_id => @player.id)
		add_breadcrumb @spellbook.name
	end

	def new
		@spellbook = SpellBook.new
		@spellbook.character_id = @character.id
	end

	def create
		@spellbook = SpellBook.new(spellbook_params)
		@spellbook.character_id = @character.id
		if @spellbook.save
			flash[:notice] = "Spellbook created!"
			redirect_to spell_book_path(@spellbook, :character_id => @character.id)
		else
			render 'new'
		end
	end

	def edit
		@spellbook = SpellBook.find(params[:id])
	end

	def update
		@spellbook = SpellBook.find(params[:id])
		if @spellbook.update_attributes(spellbook_params)
			flash[:notice] = "Spellbook updated successfully..."
			redirect_to(spell_book_path(@spellbook, :character_id => @character.id))
		else
			render('edit')
		end
	end

	def delete
		@spellbook = SpellBook.find(params[:id])
	end

	def destroy
		@spellbook = SpellBook.find(params[:id])
		@spellbook.destroy
		flash[:notice] = "Spellbook deleted!"
		redirect_to character_path(@character, :player_id => @player.id)
	end


	def inscribe
		@spellbook = SpellBook.find(params[:id])
		params[:inscribe_spells].each do |spell|
			@new_spell = Spell.find(spell)
			@spellbook.spells << @new_spell
		end
		redirect_to(spell_book_path(@spellbook, :character_id => @character.id))
	end

	def erase
		@spellbook = SpellBook.find(params[:id])
		@spell = Spell.find(params[:spell_id])
		@spellbook.spells.delete (@spell)
		redirect_to(spell_book_path(@spellbook, :character_id => @character.id))
	end

	def print
		@spellbook = SpellBook.find(params[:id])
		@spells = @spellbook.spells.sorted_name
	end




	private

	def find_char_and_player
		@character = Character.find(params[:character_id])
		@player = Player.find(@character.player_id)
	end

	def spellbook_params
		params.require(:spell_book).permit(
			:name,
			:description,
			:character_id
		)
	end

	def resolve_layout
		case action_name
			when "print"
				"print_spells"
			else
				"main"
		end
	end



end

app/helpers/spell_books_helper.rb
module SpellBooksHelper
end

app/views/spell_books/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Spellbook form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= f.text_field(:description) %></td>
  </tr>
</table>

app/views/spell_books/delete.html.erb
<% 
	@page_title = "Confirm Delete" 
%>


<% content_for :sidebar do %>

<% end %>

<% content_for :main_content do %>
		<div style="text-align: center;">
			<%= form_for(@spellbook, :url => spell_book_path(@spellbook, :character_id => @character.id), :method => 'delete') do |f| %>
				<h2>
					Are you sure you want to delete this spell book:
				</h2>
				<h2>
					<%= f.object.name %>?
				</h2>
				<h2>
					Note:  All spells will be lost!
				</h2>
				<p>
					<%= f.submit("Yes, delete!", :class => 'btn-green') %>
				</p>
				<p>
					<%= link_to("Cancel", spell_book_path(@spellbook, :character_id => @character.id), :class => "btn-red") %>
				</p>
				
			<% end %>
		</div>

<% end %>

app/views/spell_books/edit.html.erb
<% @page_title = "Edit Spellbook" %>


<% content_for :sidebar do %>
<ul id="sidebar-nav">
	<li>
		<%= link_to("Cancel", spell_book_path(@spellbook, :character_id => @character.id), :class => 'btn-red') %>
	</li>
</ul>
<% end %>

<% content_for :main_content do %>
	<div class="spellbook edit">

	  <%= form_for(@spellbook, :url => spell_book_path(@spellbook, :character_id => @character.id)) do |f| %>

	    <%= render(:partial => 'form', :locals => {:f => f}) %>

	    <div class="form-buttons">
	      <%= f.submit("Update Spellbook", :class => "btn-green") %>
	    </div>

	  <% end %>
	</div>
<% end %>

app/views/spell_books/new.html.erb
<% @page_title = "Add Spellbook" %>


<% content_for :sidebar do %>
<ul id="sidebar-nav">
	<li>
		<%= link_to("Cancel", character_path(@character, :player_id => @player.id), :class => 'btn-red') %>
	</li>
</ul>
<% end %>

<% content_for :main_content do %>
	<div class="spellbook add">

	  <%= form_for(@spellbook, :url => spell_books_path(:character_id => @character.id)) do |f| %>

	    <%= render(:partial => 'form', :locals => {:f => f}) %>

	    <div class="form-buttons">
	      <%= f.submit("Create Spellbook", :class => "btn-green") %>
	    </div>

	  <% end %>
	</div>
<% end %>

app/views/spell_books/show.html.erb
<% 
	@page_title = @spellbook.name 
%>


<% content_for :sidebar do %>
	<ul id="sidebar-nav">
		<li>
			<%= link_to("Edit", edit_spell_book_path(@spellbook,:character_id => @character.id), :class => 'btn-green') %>
		</li>
		<li>
			<%= link_to("Delete", delete_spell_book_path(@spellbook, :character_id => @character.id), :class => 'btn-red') %>
		</li>
	</ul>
<% end %>

<% content_for :main_content do %>
		<p><%= render_breadcrumbs %></p>
		<%= render(:partial => 'application/flash_notify') %>
	
		<div id="spellbook_details">
			<h2>Spellbook: <%= @spellbook.name %></h2>
			<p>
				<%= @spellbook.description %><br></%>
			</p>
			<p>
				<br><%= link_to("Print", print_spell_book_path(@spellbook, :character_id => @character.id), :target => "_blank", :class => "btn-green") %>
			</p>
		</div>
		<div id="spellbook_spells">
			<div id="inscribed">
				<h2>Inscribed Spells:</h2>
				<% if @spellbook.spells.count == 0 %>
					<p>No spells have been inscribed</p>
				<% else %>

				<p>Click headings to sort...</p>
				<table id="spell-table">
					<tr>
						<th onclick="sortTable(0)">Name</th>
						<th onclick="sortTable(1)">Level</th>
						<th onclick="sortTable(2)">School</th>
						<th>X</th>
					</tr>
					<% @spellbook.spells.each do |spell| %>
						<tr>
							<td><%= link_to spell.name, spell_path(spell) %></td>
							<td><%= spell.level_display %></td>
							<td><%= spell.school %></td>
							<td><%= link_to("X", erase_spell_book_path(@spellbook, :spell_id => spell.id, :character_id => @character.id, :method => :delete), :class => 'btn-red') %></td>
						</tr>
					<% end %>
				</table>
				<% end %>
			</div><!-- end #inscribed -->

			<div id="spell_list">
				<h2>All Spells:</h2>
				<%= form_for(@spellbook, :url => inscribe_spell_book_path(@spellbook, :character_id => @character.id), :method => :post) do |f| %>
				<p>
					<%= select_tag("inscribe_spells[]", options_for_select(@spell_options), {:multiple => true, :size => 10}) %>
					<br><%= f.submit("Inscribe", :class => "btn-green") %>
				</p>
				<% end %>
			</div>
			<div style="clear:both;"
		</div>
<% end %> <!-- main content -->