config/routes.rb
Rails.application.routes.draw do

	root 'players#index'


  get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'

  get 'inscriptions/create'
  get 'inscriptions/destroy'


	get '/meta', to: 'main#meta'

	resources :players, :characters, :spells, :spell_books, :feats do
		member do
			get :delete
		end
	end

	resources :spell_books do
		member do
			post :inscribe
			get :erase
			get :print
		end
	end

	resources :characters do
		member do
			post :train_feat
			get :untrain_feat
			get :print_feats
			get :edit_feat_uses
			post :update_feat_uses
		end
	end

	resources :character_classes
	resources :races

end

app/models/character.rb
class Character < ApplicationRecord


	validates :name,
		:presence => true
	validates :level,
		:presence => true
	validates :character_class,
		:presence => true
	validates :race,
		:presence => true

	belongs_to :player
	has_many :spell_books,
		:dependent => :destroy
	has_many :trainings
	has_many :feats, 
		:through => :trainings,
		:dependent => :destroy


	def summary
		self[:level].ordinalize + ' level ' + self[:race] + ' ' + self[:character_class]
	end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  	skip_before_action :verify_authenticity_token

	before_action :find_player

  	layout :resolve_layout
  	add_breadcrumb "home", :root_path
  	add_breadcrumb "Players", '\players'

  

	def show
		@character = Character.find(params[:id])
		feat_list = @character.feats.count > 0 ? Feat.sorted - @character.feats : Feat.sorted
		@feat_options = feat_list.map{|spell| [spell.name, spell.id]}
		add_breadcrumb @player.name, player_path(@player)
		add_breadcrumb @character.name
	end

	def edit
		@character = Character.find(params[:id])
	end

	def update
		@character = Character.find(params[:id])
		if @character.update_attributes(character_params)
			flash[:notice] = "Character updated successfully..."
			redirect_to(character_path(@character, :player_id => @player.id))
		else
			render('edit')
		end
	end

	def new
		@character = Character.new
		@character.player_id = params[:player_id]
	end

	def create
		@character = Character.new(character_params)
		@character.player_id = @player.id
		if @character.save
			flash[:notice] = "Character created!"
			redirect_to player_path(@player)
		else
			render 'new'
		end
	end

	def delete
		@character = Character.find(params[:id])
	end

	def destroy
		@character = Character.find(params[:id])
		@character.destroy
		flash[:notice] = "Character deleted!"
		redirect_to player_path(@player)
	end


	def train_feat
		@character = Character.find(params[:id])
		params[:train_feats].each do |feat|
			@character.feats << Feat.find(feat)
		end
		redirect_to(character_path(@character, :player_id => @player.id))
	end

	def untrain_feat
		@character = Character.find(params[:id])
		@character.feats.delete (Feat.find(params[:feat_id]))
		redirect_to(character_path(@character, :player_id => @player.id))
	end

	def print_feats
		@character = Character.find(params[:id])
		@feats = @character.feats.sorted_type
	end

	def edit_feat_uses
		@character = Character.find(params[:id])
		@training = @character.trainings.where(:feat_id => params[:feat_id]).first
		@feat = Feat.find(params[:feat_id])

	end

	def update_feat_uses
		@character = Character.find(params[:id])
		@training = @character.trainings.where(:feat_id => params[:feat_id]).first
		@feat = Feat.find(params[:feat_id])
		@training.custom_uses_count = params[:character][:trainings][:custom_uses_count]
		@training.notes = params[:character][:trainings][:notes]
		if @training.save
			flash[:notice] = "Uses count updated..."
			redirect_to(character_path(@character, :player_id => @player.id))
		else
			render('edit_feat_uses')
		end
	end


	private

	def find_player
		@player = Player.find(params[:player_id])
	end

	def character_params
		params.require(:character).permit(
			:name,
			:race,
			:character_class,
			:level
		)
	end

	def resolve_layout
		case action_name
			when "print_feats"
				"print_feats"
			else
				"main"
		end
	end

	
end

app/helpers/characters_helper.rb
module CharactersHelper
	def feat_uses_display(feat)
		if feat.uses != 'custom'
			feat.uses
		else
			text = @character.trainings.where(:feat_id => feat).first.custom_uses_count || 'edit'
			link_to(text, edit_feat_uses_character_path(@character,:feat_id => feat.id, :player_id => @player.id))
		end
	end

	def feat_notes_display(feat)
		# custom_note = @character.trainings.where(:feat_id => feat).first.notes
		if has_notes(feat)
			note_indicator = "Y"
		else
			note_indicator = "N"
		end
		link_to(note_indicator, edit_feat_uses_character_path(@character,:feat_id => feat.id, :player_id => @player.id))
	end

	def has_notes(feat)
		custom_note = @character.trainings.where(:feat_id => feat).first.notes
		if custom_note.nil? || custom_note.length < 1
			false
		else
			true
		end
	end

	def feat_use_counter(feat)
		count = 0
		case feat.uses
			when "NA"
				# Do nothing
			when "custom"
				custom_count = @character.trainings.where(:feat_id => feat).first.custom_uses_count || 0
				if custom_count > 0 
					count = custom_count.to_i
				end
			else
				count = feat.uses.to_i
		end
		count > 0 ? count : nil
	end
end

app/views/characters/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Character form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Race</th>
    <td><%= f.collection_select(:race, Race.sorted, :name, :name, :selected => "Human") %></td>
  </tr>
  <tr>
    <th>Class</th>
    <td><%= f.collection_select(:character_class, CharacterClass.sorted, :name, :name, :prompt => "Choose a class") %></td>
  </tr>
  <tr>
    <th>level</th>
    <td><%= f.select :level, (1..20) %></td>
  </tr>
  
</table>


app/views/characters/_uses_form.html.erb
<%= error_messages_for(f.object) %>



<table summary="Feat uses form fields">
  <tr>
  	<% if @feat.uses == 'custom' %>
    <th>Custom Uses</th>
    	
      <%= f.fields_for :trainings, @training do |training| %>
        <td><%= training.text_field :custom_uses_count %></td>
      <% end %>
  </tr>
  <% end %>

  <tr>
    <th>Notes</th>
      <%= f.fields_for :trainings, @training do |training| %>
        <td><%= training.text_area :notes, size: "30x10" %></td>
      <% end %>
  </tr>

</table>

<!-- WYSIWYG -->

app/views/characters/delete.html.erb
<% 
	@page_title = "Confirm Delete" 
%>


<% content_for :sidebar do %>

<% end %>

<% content_for :main_content do %>
		<div style="text-align: center;">
			<%= form_for(@character, :url => character_path(@character, :player_id => @player.id), :method => 'delete') do |f| %>
				<h2>
					Are you sure you want to delete this character:
				</h2>
				<h2>
					<%= f.object.name %>?
				</h2>
				<h2>
					Note:  This cannot be undone!
				</h2>
				<p>
					<%= f.submit("Yes, delete!", :class => 'btn-green') %>
				</p>
				<p>
					<%= link_to("Cancel", character_path(@character, :player_id => @player.id), :class => "btn-red") %>
				</p>
				
			<% end %>
		</div>

<% end %>

app/views/characters/edit.html.erb
<% @page_title = "Add Character" %>
<% @menu_item = "Players" %>


<% content_for :sidebar do %>
	<ul id="sidebar-nav">
		<li> 
			<%= link_to("Cancel", character_path(@character, :player_id => @player.id), :class => 'btn-red') %>
		</li>
	</ul>
<% end %>

<% content_for :main_content do %>
	<div class="character edit">

	  <%= form_for(@character, :url => character_path(@character, :player_id => @player.id)) do |f| %>

	    <%= render(:partial => 'form', :locals => {:f => f}) %>

	    <div class="form-buttons">
	      <%= f.submit("Update Character", :class => "btn-green") %>
	    </div>

	  <% end %>
	</div>
<% end %>

app/views/characters/edit_feat_uses.html.erb
<% 
	@page_title = @player.name 
%>


<script type="text/javascript">
		openTab(event, 'feats')
</script>


<% content_for :sidebar do %>
	<%= link_to("Cancel", character_path(@character, :player_id => @player.id), :class => 'btn-red') %>
<% end %>

<% content_for :main_content do %>
		<p><%= render_breadcrumbs %></p>
		<%= render(:partial => 'application/flash_notify') %>
	
		<div id="player_details">
			<h2><%= @player.name %></h2>
			<p>
				<%= @player.email %><br></%>
				<%= @player.phone %>
			</p>
		</div>

		<div id="character_details">
			<h2><%= @character.name %></h2>
			<p>
				<%= @character.summary %> 
			</p>
		</div>
		<h2><%= @feat.name %></h2>
		<p><%= raw sanitize @feat.description, tags: %w(strong em p ), attributes: %w(href) %></p>

		<%= form_for(@character, :url => update_feat_uses_character_path(@character, :feat_id => @feat.id, :player_id => @player.id), :method => :update) do |f| %>

	    <%= render(:partial => 'uses_form', :locals => {:f => f}) %>

	    <div class="form-buttons">
	      <%= f.submit("Update", :class => "btn-green") %>
	    </div>

	  <% end %>
	</div>
<% end %>

app/views/characters/new.html.erb
<% @page_title = "Add Character" %>
<% @menu_item = "Players" %>


<% content_for :sidebar do %>
	<ul id="sidebar-nav">
		<li> 
			<%= link_to("Cancel", player_path(@player), :class => 'btn-red') %>
		</li>
	</ul>
<% end %>

<% content_for :main_content do %>
	<div class="character add">

	  <%= form_for(@character, :url => characters_path(:player_id => @player.id)) do |f| %>

	    <%= render(:partial => 'form', :locals => {:f => f}) %>

	    <div class="form-buttons">
	      <%= f.submit("Add Character", :class => "btn-green") %>
	    </div>

	  <% end %>
	</div>
<% end %>

app/views/characters/print_feats.html.erb
<% yield %>

app/views/characters/show.html.erb
<% 
	@page_title = @player.name 
%>


<script type="text/javascript">
		openTab(event, 'feats')
</script>


<% content_for :sidebar do %>
	<ul id="sidebar-nav">
		<li>
			<%= link_to("Edit", edit_character_path(@character,:player_id => @player.id), :class => 'btn-green') %>
		</li>
		<li>
			<%= link_to("Delete", delete_character_path(@character, :player_id => @player.id), :class => 'btn-red') %>
		</li>
	</ul>
<% end %>

<% content_for :main_content do %>
		<p><%= render_breadcrumbs %></p>
		<%= render(:partial => 'application/flash_notify') %>
	
		<div id="player_details">
			<h2><%= @player.name %></h2>
			<p>
				<%= @player.email %><br></%>
				<%= @player.phone %>
			</p>
		</div>

		<div id="character_details">
			<h2><%= @character.name %></h2>
			<p>
				<%= @character.summary %> 
			</p>
		</div>

<div class="tab">
  <button class="tablinks active" onclick="openTab(event, 'feats')">Feats</button>
  <button class="tablinks" onclick="openTab(event, 'spellbooks')">Spellbooks</button>
</div>

<div id="feats" class="tabcontent">
	<h4>Feats:</h4>
		<div id="trained_feats">
			<h2>Trained Feats:</h2>
			<% if @character.feats.count == 0 %>
				<p>No feats have been trained</p>
			<% else %>
			<%= link_to("Print Feats", print_feats_character_path(@character, :player_id => @player.id), :target => "_blank", :class => 'btn-green') %>
			<p>Click headings to sort...</p>
			<table id="spell-table">
				<tr>
					<th onclick="sortTable(0)">Name</th>
					<th onclick="sortTable(1)">Type</th>
					<th onclick="sortTable(2)">Uses</th>
					<th onclick="sortTable(3)">Notes</th>
					<th>X</th>
				</tr>
				<% @character.feats.sorted.each do |feat| %>
					<tr>
						<td><%= link_to feat.name, feat_path(feat) %></td>
						<td><%= feat.use_type %></td>
						<td>
							<%= feat_uses_display(feat) %>
						</td>
						<td><%= feat_notes_display(feat) %> </td>
						<td><%= link_to("X", untrain_feat_character_path(@character, :feat_id => feat.id, :character_id => @character.id, :player_id => @player.id, :method => :delete), :class => 'btn-red') %></td> 
					</tr>
				<% end %>
			</table>
			<% end %>
		</div><!-- end #inscribed -->

		<div id="all_feats">
			<h2>All Feats:</h2>
			<%= form_for(@character, :url => train_feat_character_path(@character, :character_id => @character.id, :player_id => @player.id), :method => :post) do |f| %>
				<p>
					<%= select_tag("train_feats[]", options_for_select(@feat_options), {:multiple => true, :size => 10}) %>
					<br><%= f.submit("Train", :class => "btn-green") %>
				</p>
				<% end %>
		</div>
			<div style="clear:both;"></div>
</div>


<div id="spellbooks" class="tabcontent">

	<h4>Spell Books:</h4>
	<% if @character.spell_books.count == 0 %>
	<p>
		No Spellbooks have been created for this character.
	</p>
	<% else %>
	<table id="spellbook-table">
		<% @character.spell_books.each do |book| %>
		<tr>
			<td><%= link_to(book.name, spell_book_path(book, :character_id => @character.id)) %></td>
			<td>Print</td>
		</tr>
		<% end %>
	</table>
	<% end %>
	<%= link_to("Add Spellbook", new_spell_book_path(:character_id => @character.id), :class => "btn-green") %>
</div> 
	


<% end %>