config/routes.rb
Rails.application.routes.draw do

	root 'players#index'


  get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'

  get 'inscriptions/create'
  get 'inscriptions/destroy'


	get '/meta', to: 'main#meta'

	resources :players, :characters, :spells, :spell_books, :feats do
		member do
			get :delete
		end
	end

	resources :spell_books do
		member do
			post :inscribe
			get :erase
			get :print
		end
	end

	resources :characters do
		member do
			post :train_feat
			get :untrain_feat
			get :print_feats
			get :edit_feat_uses
			post :update_feat_uses
		end
	end

	resources :character_classes
	resources :races

end

app/models/player.rb
class Player < ApplicationRecord

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :name,
		:presence => true,
		:uniqueness => true

	validates :email,
		:uniqueness => true,
		:format => EMAIL_REGEX,
		:allow_blank => true

	has_many :characters,
		:dependent => :destroy
	
	
	
	scope :sorted, lambda { order("name ASC") }
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	layout 'main'

	add_breadcrumb "home", :root_path

	def index
		@players = Player.sorted
		add_breadcrumb "Players"
	end

	def show
		@player = Player.find(params[:id])
		add_breadcrumb "Players", players_path
		add_breadcrumb @player.name
	end

	def new
		@player = Player.new
	end

	def create
		@player = Player.new(player_params)
		if @player.save
			flash[:notice] = "Player created!"
			redirect_to player_path(@player)
		else
			render 'new'
		end
	end


	def edit
		@player = Player.find(params[:id])
	end

	def update
		@player = Player.find(params[:id])
		if @player.update_attributes(player_params)
			flash[:notice] = "Player updated successfully..."
			redirect_to(player_path(@player))
		else
			render('edit')
		end
	end

	def delete
		@player = Player.find(params[:id])
	end

	def destroy
		@player = Player.find(params[:id])
		@player.destroy
		flash[:notice] = "Player deleted!"
		redirect_to players_path
	end


	private

	def player_params
		params.require(:player).permit(
			:name,
			:email,
			:phone
		)
	end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Player form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= f.email_field(:email) %></td>
  </tr>
  <tr>
    <th>Phone</th>
    <td><%= f.text_field(:phone) %></td>
  </tr>
</table>

app/views/players/delete.html.erb
<% 
	@page_title = "Confirm Delete" 
%>


<% content_for :sidebar do %>
	<p>Actions:</p>
	<p>
		<%= link_to("Cancel", player_path(@player), :class => 'btn-red') %>
	</p>
<% end %>

<% content_for :main_content do %>
		<div style="text-align: center;">
			<%= form_for(@player, :method => 'delete') do |f| %>
				<h2>
					Are you sure you want to delete this player:
				</h2>
				<h2>
					<%= f.object.name %>?
				</h2>
				<h2>
					Note:  This cannot be undone!
				</h2>
				<p>
					<%= f.submit("Yes, delete!", :class => 'btn-green') %>
				</p>
			<% end %>
		</div>
<% end %>

app/views/players/edit.html.erb
<% @page_title = "Edit Player" %>
<% @menu_item = "Players" %>


<% content_for :sidebar do %>
	<ul id="sidebar-nav">
		<li> 
			<%= link_to("Cancel", player_path(@player), :class => 'btn-red') %>
		</li>
	</ul>
<% end %>

<% content_for :main_content do %>
	<div class="player edit">

	  <%= form_for(@player) do |f| %>

	    <%= render(:partial => 'form', :locals => {:f => f}) %>

	    <div class="form-buttons">
	      <%= f.submit("Update Player", :class => "btn-green") %>
	    </div>

	  <% end %>
	</div>
<% end %>

app/views/players/index.html.erb
<% 
	@page_title = "Players" 
	@menu_item = "Players"
%>


<% content_for :sidebar do %>
	<ul id="sidebar-nav">
		<li>
			<%= link_to("Add Player", new_player_path, :class => 'btn-green') %>
		</li>
	</ul>
<% end %>

<% content_for :main_content do %>
	<p><%= render_breadcrumbs %></p>
	<%= render(:partial => 'application/flash_notify') %>


		<h2>Current Players:</h2>
		<% if @players.count == 0 %>
			<p>No players currently exist...</p>
		<% else %>
		
		<table id="player-table">
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Phone</th>
				<!-- <th>Campaigns</th> -->
			</tr>
			<% @players.each do |player| %>
				<tr>
					<td><%= link_to(player.name, player_path(player)) %></td>
					<td><%= player.email %></td>
					<td><%= player.phone %></td>
				</tr>
			<% end %>
		</table>
		<% end %>

<% end %>

app/views/players/new.html.erb
<% @page_title = "Add Player" %>
<% @menu_item = "Players" %>


<% content_for :sidebar do %>
<ul id="sidebar-nav">
	<li>
		<%= link_to("Cancel", players_path, :class => 'btn-red') %>
	</li>
</ul>
<% end %>

<% content_for :main_content do %>
	<div class="player add">

	  <%= form_for(@player) do |f| %>

	    <%= render(:partial => 'form', :locals => {:f => f}) %>

	    <div class="form-buttons">
	      <%= f.submit("Create Player", :class => "btn-green") %>
	    </div>

	  <% end %>
	</div>
<% end %>

app/views/players/show.html.erb
<% 
	@page_title = @player.name 
	@menu_item = "Players"
%>


<% content_for :sidebar do %>
	<ul id="sidebar-nav">
		<li>
			<%= link_to("Edit", edit_player_path(@player), :class => 'btn-green') %>
		</li>
		<li>
			<%= link_to("Delete", delete_player_path(@player), :class => 'btn-red') %>
		</li>
	</ul>
<% end %>

<% content_for :main_content do %>
		<p><%= render_breadcrumbs %></p>
		<%= render(:partial => 'application/flash_notify') %>
	
		<div id="player_details">
			<h2><%= @player.name %></h2>
			<p>
				<%= @player.email %><br></%>
				<%= @player.phone %>
			</p>
		</div>

		<div id="player_characters">
			<h3>Characters:</h3>

			<% if @player.characters.count == 0 %>
			<p>No characters currently exist for this player...</p>
			<% else %>
				<table>
					<tr>
						<th>Name</th>
						<th>Details</th>
					</tr>
				<% @player.characters.each do |char| %>
					<tr>
						<td><%= link_to(char.name, character_path(char, :player_id => @player.id) )%></td>
						<td><%= char.summary %> </td>
					</tr>
				<% end %>
				</table>
			<% end %>
			<p>
				<%= link_to("Add Character", new_character_path(:player_id => @player.id), :class => "btn-green") %>
			</p>

		</div>
<% end %>