config/routes.rb
Rails.application.routes.draw do

	root 'players#index'


  get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'

  get 'inscriptions/create'
  get 'inscriptions/destroy'


	get '/meta', to: 'main#meta'

	resources :players, :characters, :spells, :spell_books, :feats do
		member do
			get :delete
		end
	end

	resources :spell_books do
		member do
			post :inscribe
			get :erase
			get :print
		end
	end

	resources :characters do
		member do
			post :train_feat
			get :untrain_feat
			get :print_feats
			get :edit_feat_uses
			post :update_feat_uses
		end
	end

	resources :character_classes
	resources :races

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	has_secure_password

	validates :user_name,
		:uniqueness => true
	validates :password,
		:presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord


	validates :name,
		:presence => true
	validates :level,
		:presence => true
	validates :character_class,
		:presence => true
	validates :race,
		:presence => true

	belongs_to :player
	has_many :spell_books,
		:dependent => :destroy
	has_many :trainings
	has_many :feats, 
		:through => :trainings,
		:dependent => :destroy


	def summary
		self[:level].ordinalize + ' level ' + self[:race] + ' ' + self[:character_class]
	end
end

app/models/character_class.rb
class CharacterClass < ApplicationRecord

	validates :name,
		:presence => true,
		:uniqueness => true


	scope :sorted, lambda { order("name ASC") }
end

app/models/feat.rb
class DescriptionValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if value.blank? || value.strip == "<p><br></p>"
      record.errors[attribute] << (options[:message] || "cannot be blank.") 
    end
  end
end


class Feat < ApplicationRecord

	META = ["id", "created_at", "updated_at"]
	VALIDATED = Feat.attribute_names.reject{|attr| META.include?(attr)}

	validates_presence_of VALIDATED

	validates :name,
		:uniqueness => true

	has_many :trainings
	has_many :characters, 
		:through => :trainings,
		:dependent => :destroy

	scope :sorted_type, lambda { order("use_type ASC, name ASC") }
	scope :sorted, lambda { order("name ASC") }

end

app/models/inscription.rb
class Inscription < ApplicationRecord
	belongs_to :spell
	belongs_to :spell_book
end

app/models/player.rb
class Player < ApplicationRecord

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :name,
		:presence => true,
		:uniqueness => true

	validates :email,
		:uniqueness => true,
		:format => EMAIL_REGEX,
		:allow_blank => true

	has_many :characters,
		:dependent => :destroy
	
	
	
	scope :sorted, lambda { order("name ASC") }
end

app/models/race.rb
class Race < ApplicationRecord

	validates :name,
		:presence => true,
		:uniqueness => true


	scope :sorted, lambda { order("name ASC") }
end

app/models/spell.rb
class DescriptionValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if value.blank? || value.strip == "<p><br></p>"
      record.errors[attribute] << (options[:message] || "cannot be blank.") 
    end
  end
end



class Spell < ApplicationRecord
	META = ["id", "created_at", "updated_at", "ritual"]
	VALIDATED = Spell.attribute_names.reject{|attr| META.include?(attr)}

	validates_presence_of VALIDATED

	validates :description,
		description: true

	has_many :inscriptions
	has_many :spell_books, 
		:through => :inscriptions,
		:dependent => :destroy

	scope :sorted_name, lambda { order("name ASC") }
	scope :sorted_level, lambda { order("level ASC name ASC") }



	def level_display
		if self[:level] == 0
			"Cantrip"
		else
			self[:level].ordinalize
		end
	end

	def self.schools
		%w(
			Abjuration
			Conjuration
			Divination
			Enchantment
			Evocation
			Illusion
			Necromancy
			Transmutation
		)
	end

	def self.casting_times
		[
			"Action",
			"Bonus Action",
			"Reaction",
			"1 minute",
			"10 minutes"
		]
	end

	def self.ranges
		[
			"Self",
			"Self (15' cone)",
			"Self (15' cube)",
			"Touch",
			"10 feet",
			"30 feet",
			"60 feet",
			"90 feet",
			"120 feet",
			"150 feet"
		]
	end

	def self.durations
		[
			"Instantaneous",
			"1 round",
			"1 hour",
			"1 minute",
			"10 minutes",
			"Concentration, up to 1 round",
			"Concentration, up to 1 minute",
			"Concentration, up to 10 minutes",
			"Concentration, up to 1 hour",
			"Concentration, up to 8 hours",
			"8 hours",
			"24 hours",
			"10 days",
			"Until dispelled"
		]
	end

	def byline
		byline = ""
		if self[:level] == 0
			byline << self[:school] + " Cantrip"
		else
			byline << self[:level].ordinalize + "-level " + self[:school]
		end

		unless self[:ritual].nil? || self[:ritual] == false
			byline << " (ritual)"
		end
		byline
	end
end

app/models/spell_book.rb
class SpellBook < ApplicationRecord

	belongs_to :character
	has_many :inscriptions
	has_many :spells, 
		:through => :inscriptions,
		:dependent => :destroy
	

	validates :name,
		:presence => true,
		:uniqueness => {
			:scope => :character_id,
			:message => "must be unique"
		}

	scope :sorted_name, lambda { order("name ASC") }
end

app/models/training.rb
class Training < ApplicationRecord
	belongs_to :character
	belongs_to :feat

	validates :custom_uses_count,
		:numericality => true,
		:allow_blank => true
end

app/controllers/delete.rb
class RaceController < ApplicationController

	skip_before_action :verify_authenticity_token, :only => :destroy


	def index
		@races = Race.sorted
	end

	def show
		@race = Race.find(params[:id])
	end

	def new
		@race = Race.new
	end

	def create
		@race = Race.new(race_params)
		@race.name.capitalize!
		if @race.save
			flash[:notice] = "Race added..."
			redirect_to races_path
		else
			render 'new'
		end
	end

	def edit
		@race = Race.find(params[:id])
	end

	def update
		@race = Race.find(params[:id])
		if @race.update_attributes(race_params)
			flash[:notice] = "Race updated..."
			redirect_to(races_path)
		else
			render('edit')
		end
	end

	def destroy
		@race = Race.find(params[:id])
		@race.destroy
		redirect_to races_path
	end


	private

	def race_params
		params.require(:character_class).permit(
			:name
		)
	end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def error_messages_for(object)
		render(:partial => 'application/error_messages', :locals => {:object => object})
	end

	def html_description(html_text)
		if html_text
			raw sanitize html_text, tags: %w(strong em p br ul ol li), attributes: %w(href)
		else
			false
		end
	end
end

app/helpers/characters_helper.rb
module CharactersHelper
	def feat_uses_display(feat)
		if feat.uses != 'custom'
			feat.uses
		else
			text = @character.trainings.where(:feat_id => feat).first.custom_uses_count || 'edit'
			link_to(text, edit_feat_uses_character_path(@character,:feat_id => feat.id, :player_id => @player.id))
		end
	end

	def feat_notes_display(feat)
		# custom_note = @character.trainings.where(:feat_id => feat).first.notes
		if has_notes(feat)
			note_indicator = "Y"
		else
			note_indicator = "N"
		end
		link_to(note_indicator, edit_feat_uses_character_path(@character,:feat_id => feat.id, :player_id => @player.id))
	end

	def has_notes(feat)
		custom_note = @character.trainings.where(:feat_id => feat).first.notes
		if custom_note.nil? || custom_note.length < 1
			false
		else
			true
		end
	end

	def feat_use_counter(feat)
		count = 0
		case feat.uses
			when "NA"
				# Do nothing
			when "custom"
				custom_count = @character.trainings.where(:feat_id => feat).first.custom_uses_count || 0
				if custom_count > 0 
					count = custom_count.to_i
				end
			else
				count = feat.uses.to_i
		end
		count > 0 ? count : nil
	end
end

app/helpers/feats_helper.rb
module FeatsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DndTools</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
    	DndTools
    	<%= 
    		unless @page_title.nil?
    			" | #{@page_title}"
    		end
    	%> 
	</title>

    <%= stylesheet_link_tag('application', media: 'all') %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.quilljs.com/1.1.6/quill.snow.css" rel="stylesheet">

  </head>




	<body class="<%= @menu_item || ''%>">

		<header id="site-header">
			<h1>DND Tools</h1>
			<nav id="main-nav">
				<ul>
					<li class="Players"><%= link_to("Players", players_path) %></a></li>
					<!-- <li><a href="#">Campaigns</a></li> -->
					<li class="Feats"><%= link_to("Feats",feats_path) %></li>
					<li class="Spells"><%= link_to("Spells", spells_path) %></li>
					<li class="Meta"><%= link_to("Meta", character_classes_path) %></li>
				</ul>
				
			</nav>

		</header>

		
		<section id="main-content">
			<section id="sidebar">
				<%= yield :sidebar %>
				<%= link_to "logout", access_logout_path %>
			</section>

			<section id="main">
				<%= yield :main_content %>
			</section>

			<%= yield %>
		
		</section>


	</body>
  </div>
</html>

app/views/layouts/print_feats.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      DndTools
      <%= 
        unless @page_title.nil?
          " | #{@page_title}"
        end
      %> 
  </title>

    <%= stylesheet_link_tag('application', media: 'all') %>

  </head>




  <body id="printable_spells">

  <div id="main">
    <h1>
      <%= @character.name %>: Feats List
    </h1>
  </div>

  <section id="printable_spell_list">
    <% @feats.each do |feat| %>

    <div class="spell_entry">
      <div class="spell_header">
        <h2><%= feat.name %></h2>
        <p><%= feat.use_type %></p>
      </div>
      <table class="print_spell_details">
        <tr>
          <th>Uses</th>
          <td><%= feat_uses_display(feat) %></td>
        </tr>
        <tr>
          <th>Reset</th>
          <td><%= feat.reset %></td>
        </tr>
      </table>
      <div class="desc">
        <%= html_description(feat.description) %>
        <% if has_notes(feat)  %>
          <p>
            <br><b>Custom Notes:</b><br>
            <%= @character.trainings.where(:feat_id => feat).first.notes %>
          </p>
        <% end %>
        <% if feat_use_counter(feat) %>
          <p style="text-align: center;margin-top: 2em;"><strong>Use Counter:</strong></p>
          <p id="use_counter">
            <%= " O " * feat_use_counter(feat) %>
          </p>
        <% end %>
        
      </div>
    </div><!-- spell_entry -->
    <% end %>

  </section>

  </body>
  </div>
</html>

app/views/layouts/print_spells.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
    	DndTools
    	<%= 
    		unless @page_title.nil?
    			" | #{@page_title}"
    		end
    	%> 
	</title>

    <%= stylesheet_link_tag('application', media: 'all') %>

  </head>




	<body id="printable_spells">

  <div id="main">
    <h1>
      Spellbook:<br>
      <%= @spellbook.name %>      
    </h1>
    <p>
      <%= @spellbook.description %>
    </p>
  </div>

  <section id="printable_spell_list">
    <% @spellbook.spells.sorted_name.each do |spell| %>

    <div class="spell_entry">
      <div class="spell_header">
        <h2><%= spell.name %></h2>
        <p><%= spell.byline %></p>
      </div>
      <table class="print_spell_details">
        <tr>
          <th>Casting Time</th>
          <td><%= spell.casting_time %></td>
        </tr>
        <tr>
          <th>Range</th>
          <td><%= spell.range %></td>
        </tr>
        <tr>
          <th>Components</th>
          <td><%= spell.components %></td>
        </tr>
        <tr>
          <th>Duration</th>
          <td><%= spell.duration %></td>
        </tr>
      </table>
      <div class="desc">
        <%= html_description(spell.description) %>
      </div>
    </div><!-- spell_entry -->
    <% end %>

  </section>

	</body>
  </div>
</html>